### ISSUE TITLE
Note about tooling

### ISSUE THREAD

**Issue by dgryski** [autarch/intro-to-go-class#1]
`golint` mostly checks style issues ( https://github.com/golang/go/wiki/CodeReviewComments ).

`go vet` checks for real errors, and should possibly be enabled on save in the editor configurations.

Please mention that all Go code should be `gofmt` (also on save), but that to solve the problem of unused/missing imports `goimports` can be used.

None of these tools check for un-checked errors, but https://github.com/kisielk/errcheck does.

**Comment by autarch** [comment]
Thanks for this and all the other reports! I've updated the slides to fix all the issues you identified. If you find any others please let me know.
