### ISSUE TITLE
Test code which uses reflect doesn't handle incomplete code well

### ISSUE THREAD

**Issue by autarch** [autarch/intro-to-go-class#16]
If a student writes incomplete code that compiles and runs the tests, it's easy for the tests to panic. They probably need a lot more checks for `nil` all over the place.

**Comment by autarch** [comment]
@ribasushi - do you remember what code did this, by any chance? I'm trying to come up with an example to help replicate this. I vaguely remember it was something to do with implementing a `func` that had the right signature but maybe just returned `nil`?

**Comment by autarch** [comment]
Actually, I'm starting to wonder if this was just another instance of the bug fixed in https://github.com/stretchr/testify/pull/622

**Comment by ribasushi** [comment]
@autarch almost certainly yes - the text of the panic() was nearly identical

**Comment by autarch** [comment]
Thanks for confirming. Once that PR is merged I think the bulk of these issues will go away. It just turns out that it's fairly easy for the exercise tests to tickle that particular bug.

**Comment by autarch** [comment]
Fixed by updating the deps for the class exercises.
